In [8]:
import pandas as pd

df = pd.read_csv("/content/marketing_campaign.csv", sep="\t")

print("Initial Shape:", df.shape)
print(df.info())
print(df.isnull().sum())  #missing values
df = df.dropna(subset=["Income"])
print("After removing rows with missing Income:", df.shape)


before_dedup = df.shape[0] #removing duplicates
df = df.drop_duplicates()
after_dedup = df.shape[0]
print(f"Duplicates removed: {before_dedup - after_dedup}")


df['Education'] = df['Education'].str.strip().str.title()

df['Marital_Status'] = df['Marital_Status'].str.strip().str.title()


df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format="%d-%m-%Y", errors='coerce')


df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")


df['income'] = df['income'].astype(float)

# Print
print("\nCleaned Dataset Info:")
print(df.info())

df.to_csv("cleaned_marketing_campaign.csv", index=False)
print("Cleaned data saved as 'cleaned_marketing_campaign.csv'")

Initial Shape: (2240, 29)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB
None
ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64
After removing rows with missing Income: (2216, 29)
Duplicates removed: 0

Cleaned Dataset Info:
<class 'pandas.core.frame.DataFrame'>
Index: 2216 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2216 non-null   int64
 1   year_birth           2216 non-null   int64
 2   education            2216 non-null   object
 3   marital_status       2216 non-null   object
 4   income               2216 non-null   float64
 5   kidhome              2216 non-null   int64
 6   teenhome             2216 non-null   int64
 7   dt_customer          2216 non-null   datetime64[ns]
 8   recency              2216 non-null   int64
 9   mntwines             2216 non-null   int64
 10  mntfruits            2216 non-null   int64
 11  mntmeatproducts      2216 non-null   int64
 12  mntfishproducts      2216 non-null   int64
 13  mntsweetproducts     2216 non-null   int64
 14  mntgoldprods         2216 non-null   int64
 15  numdealspurchases    2216 non-null   int64
 16  numwebpurchases      2216 non-null   int64
 17  numcatalogpurchases  2216 non-null   int64
 18  numstorepurchases    2216 non-null   int64
 19  numwebvisitsmonth    2216 non-null   int64
 20  acceptedcmp3         2216 non-null   int64
 21  acceptedcmp4         2216 non-null   int64
 22  acceptedcmp5         2216 non-null   int64
 23  acceptedcmp1         2216 non-null   int64
 24  acceptedcmp2         2216 non-null   int64
 25  complain             2216 non-null   int64
 26  z_costcontact        2216 non-null   int64
 27  z_revenue            2216 non-null   int64
 28  response             2216 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(25), object(2)
memory usage: 519.4+ KB
None
Cleaned data saved as 'cleaned_marketing_campaign.csv'